name: UI Tests

on:
  push:
    branches:
      - automation-ci
  pull_request:
    branches:
      - automation-ci

jobs:
  build:
    name: Build
    runs-on: macos-14-arm64

    steps:
      - uses: actions/checkout@v4

      - name: Build app
        run: |
          set -o pipefail
          cd JoyfillSwiftUIExample
          xcodebuild \
            -project JoyfillExample.xcodeproj \
            -scheme JoyfillExample \
            -sdk iphonesimulator \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            EXCLUDED_ARCHS=arm64 \
            ONLY_ACTIVE_ARCH=YES \
            build \
          | xcpretty

  ui-tests:
    name: Boot Simulator & Run UI Tests
    runs-on: macos-14-arm64
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Shutdown & Erase Simulators
        run: |
          xcrun simctl shutdown all
          xcrun simctl erase all

      - name: Boot specific simulator
        run: |
          UDID="F5C7F34E-63E6-41BF-A81B-A17F2773A5CB"
          echo "Booting simulator $UDID"
          xcrun simctl boot "$UDID"
          open -a Simulator
          xcrun simctl bootstatus "$UDID" -b

      - name: Run UI Tests
        run: |
          set -o pipefail
          cd JoyfillSwiftUIExample
          xcodebuild test \
            -project JoyfillExample.xcodeproj \
            -scheme JoyfillUITests \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,OS=18.2,id=F5C7F34E-63E6-41BF-A81B-A17F2773A5CB' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            EXCLUDED_ARCHS=arm64 \
            ONLY_ACTIVE_ARCH=YES \
          | xcpretty --color --report html --output ui-test-report.html

      - name: Upload UI Test Report
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-report
          path: JoyfillSwiftUIExample/ui-test-report.html 
