name: iOS Automation CI

on:
  push:
    branches: [ "automation-ci" ]
  pull_request:
    branches: [ "automation-ci" ]

jobs:
  # 1️⃣ Build
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Build Project
        run: |
          set -o pipefail
          cd JoyfillSwiftUIExample
          xcodebuild clean build \
            -project JoyfillExample.xcodeproj \
            -scheme JoyfillExample \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            EXCLUDED_ARCHS=arm64 \
            ONLY_ACTIVE_ARCH=YES \
          | xcpretty --color --report html --output build-report.html
      - name: Upload Build Report
        uses: actions/upload-artifact@v4
        with:
          name: build-report
          path: JoyfillSwiftUIExample/build-report.html

  # 3️⃣ UI tests (after build)
  ui-tests:
    needs: build
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Reset Simulator
        run: |
          xcrun simctl shutdown all
          xcrun simctl erase all

      - name: Boot & Wait
        run: |
          UDID=$(xcrun simctl list devices \
            | grep "iPhone 16 Pro (" \
            | head -1 \
            | awk -F '[()]' '{print $2}')
          echo "Booting simulator $UDID"
          xcrun simctl boot "$UDID"
          xcrun simctl bootstatus "$UDID" -b

      - name: Run UI Tests
        run: |
          set -o pipefail
          cd JoyfillSwiftUIExample
          xcodebuild test \
            -project JoyfillExample.xcodeproj \
            -scheme JoyfillUITests \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,UDID=$UDID" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            EXCLUDED_ARCHS=arm64 \
            ONLY_ACTIVE_ARCH=YES \
          | xcpretty --color --report html --output ui-test-report.html

      - name: Upload UI Test Report
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-report
          path: JoyfillSwiftUIExample/ui-test-report.html
