name: iOS Automation CI

on:
  push:
    branches: [ "automation-ci" ]
  pull_request:
    branches: [ "automation-ci" ]

jobs:
  # 1️⃣ Build
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Build Project
        run: |
          set -o pipefail
          cd JoyfillSwiftUIExample
          xcodebuild clean build \
            -project JoyfillExample.xcodeproj \
            -scheme JoyfillExample \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES \
          | xcpretty --color --report html --output build-report.html

      - name: Upload Build Report
        uses: actions/upload-artifact@v4
        with:
          name: build-report
          path: JoyfillSwiftUIExample/build-report.html

  # 2️⃣ UI tests (after build)
  ui-tests:
    needs: build
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Reset Simulator
        run: |
          xcrun simctl shutdown all
          xcrun simctl erase all

      - name: Boot Simulator & Start GUI
        run: |
          DEVICE="iPhone 16 Pro"
          OS="18.2"
          # boot device
          xcrun simctl boot "$DEVICE" --os "$OS"
          # launch the Simulator app so UI tests can attach
          open -a Simulator
          # wait until fully booted (increase timeout to 120s)
          xcrun simctl bootstatus "$DEVICE" -b

      - name: Run UI Tests (raw logs)
        run: |
          set -o pipefail
          cd JoyfillSwiftUIExample
          xcodebuild test \
            -project JoyfillExample.xcodeproj \
            -scheme JoyfillUITests \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2' \
            -destination-timeout 120 \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES

      - name: Upload UI Test Report
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-report
          path: JoyfillSwiftUIExample/ui-test-report.html
